config/routes.rb
ResumeEdit::Application.routes.draw do
  resources :skill_suggestions

  resources :resume_feedbacks

  resources :resume_docs

  match 'resume/convert' => 'resume#convert', :as => :resume_convert
  match 'resume/critique' => 'resume#critique', :as => :resume_critique
  match 'resume/provide_critique' => 'resume#provide_critique', :as => :provide_critique
  match 'same_origin_hook' => 'resume#same_origin_hook', :as => "same_origin_hook"
  
  match 'resume/ajax_set_safe_html' => 'resume_docs#ajax_set_safe_html', :as => "ajax_set_safe_html"
  match 'resume/ajax_add_note' => 'resume_docs#ajax_add_note', :as => "ajax_add_note"
  match 'resume/ajax_add_annotation' => 'resume_docs#ajax_add_annotation', :as => "ajax_add_annotation"
  match 'resume/ajax_get_feedback' => 'resume_docs#ajax_get_feedback', :as => "ajax_get_feedback"
  match 'resume/ajax_get_skills' => 'resume_docs#ajax_get_skills', :as => "ajax_get_skills"
  match 'resume/ajax_set_poster_name' => 'resume_feedbacks#ajax_set_poster_name', :as => "ajax_set_poster_name"
  
  match 'resume/ajax_remove_feedback' => 'resume_feedbacks#ajax_remove_feedback', :as => "ajax_remove_feedback"

  match 'skill_suggestions/ajax_add_skill' => 'skill_suggestions#ajax_add_skill', :as => "ajax_add_skill"
  match 'skill_suggestions/ajax_remove_skill' => 'skill_suggestions#ajax_remove_skill', :as => "ajax_remove_skill"  
  
  

end

app/models/resume_feedback.rb
class ResumeFeedback < ActiveRecord::Base
  attr_accessible :bid, :feedback_type, :json_data, :name, :note, :resume_doc_guid
end

app/controllers/resume_feedbacks_controller.rb
class ResumeFeedbacksController < ApplicationController
  # GET /resume_feedbacks
  # GET /resume_feedbacks.json
  def index
    @resume_feedbacks = ResumeFeedback.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @resume_feedbacks }
    end
  end

  # GET /resume_feedbacks/1
  # GET /resume_feedbacks/1.json
  def show
    @resume_feedback = ResumeFeedback.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @resume_feedback }
    end
  end

  # GET /resume_feedbacks/new
  # GET /resume_feedbacks/new.json
  def new
    @resume_feedback = ResumeFeedback.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @resume_feedback }
    end
  end

  # GET /resume_feedbacks/1/edit
  def edit
    @resume_feedback = ResumeFeedback.find(params[:id])
  end

  # POST /resume_feedbacks
  # POST /resume_feedbacks.json
  def create
    @resume_feedback = ResumeFeedback.new(params[:resume_feedback])

    respond_to do |format|
      if @resume_feedback.save
        format.html { redirect_to @resume_feedback, notice: 'Resume feedback was successfully created.' }
        format.json { render json: @resume_feedback, status: :created, location: @resume_feedback }
      else
        format.html { render action: "new" }
        format.json { render json: @resume_feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /resume_feedbacks/1
  # PUT /resume_feedbacks/1.json
  def update
    @resume_feedback = ResumeFeedback.find(params[:id])

    respond_to do |format|
      if @resume_feedback.update_attributes(params[:resume_feedback])
        format.html { redirect_to @resume_feedback, notice: 'Resume feedback was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @resume_feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resume_feedbacks/1
  # DELETE /resume_feedbacks/1.json
  def destroy
    @resume_feedback = ResumeFeedback.find(params[:id])
    @resume_feedback.destroy

    respond_to do |format|
      format.html { redirect_to resume_feedbacks_url }
      format.json { head :no_content }
    end
  end
  
  def ajax_set_poster_name
  	bid = cookies[:bid]
  	name = params[:name]
  	
  	if !name.blank?
	  	cookies[:poster_name] = name
  	
  		feedbacks = ResumeFeedback.find_all_by_bid(bid)
	  	feedbacks.each do |f|
  			f.name = name
  			f.save
	  	end
	  end
  	
  	render :json => {}.to_json
  end
  
  def ajax_remove_feedback
  	bid = cookies[:bid]
  	id = params[:id]
  	
  	if !bid.blank? and !id.blank?
  		feedback = ResumeFeedback.find_by_id_and_bid(id, bid)
  		if feedback
  			feedback.destroy
  		end
  	end
  	
  	render :json => {}.to_json
  end
end

app/helpers/resume_feedbacks_helper.rb
module ResumeFeedbacksHelper
end

app/views/resume_feedbacks/_form.html.erb
<%= form_for(@resume_feedback) do |f| %>
  <% if @resume_feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resume_feedback.errors.count, "error") %> prohibited this resume_feedback from being saved:</h2>

      <ul>
      <% @resume_feedback.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :feedback_type %><br />
    <%= f.text_field :feedback_type %>
  </div>
  <div class="field">
    <%= f.label :resume_doc_guid %><br />
    <%= f.text_field :resume_doc_guid %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
  </div>
  <div class="field">
    <%= f.label :bid %><br />
    <%= f.text_field :bid %>
  </div>
  <div class="field">
    <%= f.label :json_data %><br />
    <%= f.text_area :json_data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resume_feedbacks/edit.html.erb
<h1>Editing resume_feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @resume_feedback %> |
<%= link_to 'Back', resume_feedbacks_path %>

app/views/resume_feedbacks/index.html.erb
<h1>Listing resume_feedbacks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Feedback type</th>
    <th>Resume doc guid</th>
    <th>Note</th>
    <th>Bid</th>
    <th>Json data</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resume_feedbacks.each do |resume_feedback| %>
  <tr>
    <td><%= resume_feedback.name %></td>
    <td><%= resume_feedback.feedback_type %></td>
    <td><%= resume_feedback.resume_doc_guid %></td>
    <td><%= resume_feedback.note %></td>
    <td><%= resume_feedback.bid %></td>
    <td><%= resume_feedback.json_data %></td>
    <td><%= link_to 'Show', resume_feedback %></td>
    <td><%= link_to 'Edit', edit_resume_feedback_path(resume_feedback) %></td>
    <td><%= link_to 'Destroy', resume_feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resume feedback', new_resume_feedback_path %>

app/views/resume_feedbacks/new.html.erb
<h1>New resume_feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', resume_feedbacks_path %>

app/views/resume_feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @resume_feedback.name %>
</p>

<p>
  <b>Feedback type:</b>
  <%= @resume_feedback.feedback_type %>
</p>

<p>
  <b>Resume doc guid:</b>
  <%= @resume_feedback.resume_doc_guid %>
</p>

<p>
  <b>Note:</b>
  <%= @resume_feedback.note %>
</p>

<p>
  <b>Bid:</b>
  <%= @resume_feedback.bid %>
</p>

<p>
  <b>Json data:</b>
  <%= @resume_feedback.json_data %>
</p>


<%= link_to 'Edit', edit_resume_feedback_path(@resume_feedback) %> |
<%= link_to 'Back', resume_feedbacks_path %>