config/routes.rb
ResumeEdit::Application.routes.draw do
  resources :skill_suggestions

  resources :resume_feedbacks

  resources :resume_docs

  match 'resume/convert' => 'resume#convert', :as => :resume_convert
  match 'resume/critique' => 'resume#critique', :as => :resume_critique
  match 'resume/provide_critique' => 'resume#provide_critique', :as => :provide_critique
  match 'same_origin_hook' => 'resume#same_origin_hook', :as => "same_origin_hook"
  
  match 'resume/ajax_set_safe_html' => 'resume_docs#ajax_set_safe_html', :as => "ajax_set_safe_html"
  match 'resume/ajax_add_note' => 'resume_docs#ajax_add_note', :as => "ajax_add_note"
  match 'resume/ajax_add_annotation' => 'resume_docs#ajax_add_annotation', :as => "ajax_add_annotation"
  match 'resume/ajax_get_feedback' => 'resume_docs#ajax_get_feedback', :as => "ajax_get_feedback"
  match 'resume/ajax_get_skills' => 'resume_docs#ajax_get_skills', :as => "ajax_get_skills"
  match 'resume/ajax_set_poster_name' => 'resume_feedbacks#ajax_set_poster_name', :as => "ajax_set_poster_name"
  
  match 'resume/ajax_remove_feedback' => 'resume_feedbacks#ajax_remove_feedback', :as => "ajax_remove_feedback"

  match 'skill_suggestions/ajax_add_skill' => 'skill_suggestions#ajax_add_skill', :as => "ajax_add_skill"
  match 'skill_suggestions/ajax_remove_skill' => 'skill_suggestions#ajax_remove_skill', :as => "ajax_remove_skill"  
  
  

end

app/models/resume_doc.rb
class ResumeDoc < ActiveRecord::Base
  attr_accessible :original_resume_html, :owner_name, :private_guid, :safe_resume_html
end

app/controllers/resume_docs_controller.rb
class ResumeDocsController < ApplicationController
  # GET /resume_docs
  # GET /resume_docs.json
  def index
    @resume_docs = ResumeDoc.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @resume_docs }
    end
  end

  # GET /resume_docs/1
  # GET /resume_docs/1.json
  def show
    @resume_doc = ResumeDoc.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @resume_doc }
    end
  end

  # GET /resume_docs/new
  # GET /resume_docs/new.json
  def new
    @resume_doc = ResumeDoc.new
    @resume_doc.private_guid = "RR"+(0...15).map{65.+(rand(25)).chr}.join

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @resume_doc }
    end
  end

  # GET /resume_docs/1/edit
  def edit
    @resume_doc = ResumeDoc.find(params[:id])
  end

  # POST /resume_docs
  # POST /resume_docs.json
  def create
    @resume_doc = ResumeDoc.new(params[:resume_doc])

    respond_to do |format|
      if @resume_doc.save
        format.html { redirect_to @resume_doc, notice: 'Resume doc was successfully created.' }
        format.json { render json: @resume_doc, status: :created, location: @resume_doc }
      else
        format.html { render action: "new" }
        format.json { render json: @resume_doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /resume_docs/1
  # PUT /resume_docs/1.json
  def update
    @resume_doc = ResumeDoc.find(params[:id])

    respond_to do |format|
      if @resume_doc.update_attributes(params[:resume_doc])
        format.html { redirect_to @resume_doc, notice: 'Resume doc was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @resume_doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resume_docs/1
  # DELETE /resume_docs/1.json
  def destroy
    @resume_doc = ResumeDoc.find(params[:id])
    @resume_doc.destroy

    respond_to do |format|
      format.html { redirect_to resume_docs_url }
      format.json { head :no_content }
    end
  end
  
  # PUT /resume_docs/1
  # PUT /resume_docs/1.json
  def ajax_set_safe_html
    @resume_doc = ResumeDoc.find(params[:id])

    @resume_doc.safe_resume_html = params[:html]
    @resume_doc.save
  	respond_to do |format|
			format.js
	  end
  end
  
  def ajax_add_note
  	if params[:id]
	  	@resume_feedback = ResumeFeedback.find(params[:id])
  	end
  	if @resume_feedback == nil
  		@resume_feedback = ResumeFeedback.new()
  	end
  	@resume_feedback.resume_doc_guid = params[:private_guid]
		@resume_feedback.name = params[:poster_name]
		@resume_feedback.feedback_type = 'note'
		@resume_feedback.note = params[:note]
		@resume_feedback.bid = params[:bid]
		@resume_feedback.json_data = params[:json_data]
		@resume_feedback.save

		render :json => {}.to_json
  end
  
  def ajax_add_annotation
  	if params[:id]
	  	@resume_feedback = ResumeFeedback.find(params[:id])
  	end
  	if @resume_feedback == nil
  		@resume_feedback = ResumeFeedback.new()
  	end
  	@resume_feedback.resume_doc_guid = params[:private_guid]
		@resume_feedback.name = params[:poster_name]
		@resume_feedback.feedback_type = 'annotation'
		@resume_feedback.note = params[:note]
		@resume_feedback.bid = params[:bid]
		@resume_feedback.json_data = params[:json_data]
		@resume_feedback.save

		render :json => {}.to_json
  end
  
  def ajax_get_feedback
  	private_guid = params[:guid]
  	@feedback = {}
  	
		if !private_guid.blank?
			feedbacks = ResumeFeedback.where(:resume_doc_guid => private_guid)
		
			feedbacks.each do |f|
				if @feedback[f.bid]
					@feedback[f.bid] << f
				else
					@feedback[f.bid] = [f]
				end
			end
		end
		
  	resp = {}
		resp["html"] = render_to_string(:action => "feedback", :layout => false, :locals=>{:feedback => @feedback})
		render :json => resp.to_json, :callback => params[:callback]
  end
  
  def ajax_get_skills
  	private_guid = params[:guid]
  	skills = SkillSuggestion.find_all_by_resume_doc_guid(private_guid) 	
		
  	resp = {}
		resp["html"] = render_to_string(:action => "skills", :layout => false, :locals=>{:skills => skills})
		render :json => resp.to_json, :callback => params[:callback]
  end
  
end

app/helpers/resume_docs_helper.rb
module ResumeDocsHelper
end

app/views/resume_docs/_form.html.erb
<%= form_for(@resume_doc) do |f| %>
  <% if @resume_doc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resume_doc.errors.count, "error") %> prohibited this resume_doc from being saved:</h2>

      <ul>
      <% @resume_doc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :owner_name %><br />
    <%= f.text_field :owner_name %>
  </div>
  <div class="field">
    <%= f.label :original_resume_html %><br />
    <%= f.text_area :original_resume_html %>
  </div>
  <div class="field">
    <%= f.label :safe_resume_html %><br />
    <%= f.text_area :safe_resume_html %>
  </div>
  <div class="field">
    <%= f.label :private_guid %><br />
    <%= f.text_field :private_guid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resume_docs/edit.html.erb
<h1>Editing resume_doc</h1>

<%= render 'form' %>

<%= link_to 'Show', @resume_doc %> |
<%= link_to 'Back', resume_docs_path %>

app/views/resume_docs/feedback.html.erb
<% feedback.each do |feedback| %>
<div class="Person" id="1">
	<div class="Name">
		<%= feedback[1].first.name%>
		<div class="FeedbackCount"><%= feedback[1].count%></div>
	</div>
	<% feedback[1].each do |f| %>
	<div class="Item Active" id="<%=f.id%>" data-person_id="<%=f.bid%>" data-feedback_type="<%=f.feedback_type%>" onclick="showFeedback(this);" data-payload='<%=f.json_data%>'>
		<div style="float:left;"><img src="/images/<%=(f.feedback_type == 'note')? "Note" : "Draw"%>Icon.png"></div>
		<div style="float:left;padding-left:10px;width:80%;"><%=f.note%></div>
		<div style="clear:both;"></div>
	</div>
	<div class="clear"></div>
	<% end %>
</div>
<% end %>

app/views/resume_docs/index.html.erb
<h1>Listing resume_docs</h1>

<table>
  <tr>
    <th>Owner name</th>
    <th>Original resume html</th>
    <th>Safe resume html</th>
    <th>Private guid</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resume_docs.each do |resume_doc| %>
  <tr>
    <td><%= resume_doc.owner_name %></td>
    <td><%= (resume_doc.original_resume_html.blank?) ? "blank" : "set" %></td>
    <td><%= resume_doc.safe_resume_html.blank? ? "blank" : "set" %></td>
    <td><%= resume_doc.private_guid %></td>
    <td><%= link_to 'Show', resume_doc %></td>
    <td><%= link_to 'Edit', edit_resume_doc_path(resume_doc) %></td>
    <td><%= link_to 'Destroy', resume_doc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= link_to 'View RCPage', resume_critique_path(:id => resume_doc.id) %></td>
    <td><%= link_to 'View Feedback Page', provide_critique_path(:guid => resume_doc.private_guid) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resume doc', new_resume_doc_path %>

app/views/resume_docs/new.html.erb
<h1>New resume_doc</h1>

<%= render 'form' %>

<%= link_to 'Back', resume_docs_path %>

app/views/resume_docs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Owner name:</b>
  <%= @resume_doc.owner_name %>
</p>

<p>
  <b>Original resume html:</b>
  <%= @resume_doc.original_resume_html %>
</p>

<p>
  <b>Safe resume html:</b>
  <%= @resume_doc.safe_resume_html %>
</p>

<p>
  <b>Private guid:</b>
  <%= @resume_doc.private_guid %>
</p>


<%= link_to 'Edit', edit_resume_doc_path(@resume_doc) %> |
<%= link_to 'Back', resume_docs_path %>

app/views/resume_docs/skills.html.erb
	<% skills.each do |skill| %>
	<div class="keyword_suggestion" style="display: block;">
		<div style="float:left;padding:2px;border-right:1px solid #1E608F;" onclick="removeSkill(this, <%=skill.id%>);">x&nbsp;</div>
		<div style="float:left;padding-top:2px;">&nbsp;<%=skill.skill%>&nbsp;</div>
		<div style="clear:both;"></div>
	</div>
	<% end %>