config/routes.rb
ResumeEdit::Application.routes.draw do
  resources :skill_suggestions

  resources :resume_feedbacks

  resources :resume_docs

  match 'resume/convert' => 'resume#convert', :as => :resume_convert
  match 'resume/critique' => 'resume#critique', :as => :resume_critique
  match 'resume/provide_critique' => 'resume#provide_critique', :as => :provide_critique
  match 'same_origin_hook' => 'resume#same_origin_hook', :as => "same_origin_hook"
  
  match 'resume/ajax_set_safe_html' => 'resume_docs#ajax_set_safe_html', :as => "ajax_set_safe_html"
  match 'resume/ajax_add_note' => 'resume_docs#ajax_add_note', :as => "ajax_add_note"
  match 'resume/ajax_add_annotation' => 'resume_docs#ajax_add_annotation', :as => "ajax_add_annotation"
  match 'resume/ajax_get_feedback' => 'resume_docs#ajax_get_feedback', :as => "ajax_get_feedback"
  match 'resume/ajax_get_skills' => 'resume_docs#ajax_get_skills', :as => "ajax_get_skills"
  match 'resume/ajax_set_poster_name' => 'resume_feedbacks#ajax_set_poster_name', :as => "ajax_set_poster_name"
  
  match 'resume/ajax_remove_feedback' => 'resume_feedbacks#ajax_remove_feedback', :as => "ajax_remove_feedback"

  match 'skill_suggestions/ajax_add_skill' => 'skill_suggestions#ajax_add_skill', :as => "ajax_add_skill"
  match 'skill_suggestions/ajax_remove_skill' => 'skill_suggestions#ajax_remove_skill', :as => "ajax_remove_skill"  
  
  

end

app/models/skill_suggestion.rb
class SkillSuggestion < ActiveRecord::Base
  attr_accessible :bid, :resume_doc_guid, :skill
end

app/controllers/skill_suggestions_controller.rb
class SkillSuggestionsController < ApplicationController
  # GET /skill_suggestions
  # GET /skill_suggestions.json
  def index
    @skill_suggestions = SkillSuggestion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @skill_suggestions }
    end
  end

  # GET /skill_suggestions/1
  # GET /skill_suggestions/1.json
  def show
    @skill_suggestion = SkillSuggestion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @skill_suggestion }
    end
  end

  # GET /skill_suggestions/new
  # GET /skill_suggestions/new.json
  def new
    @skill_suggestion = SkillSuggestion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @skill_suggestion }
    end
  end

  # GET /skill_suggestions/1/edit
  def edit
    @skill_suggestion = SkillSuggestion.find(params[:id])
  end

  # POST /skill_suggestions
  # POST /skill_suggestions.json
  def create
    @skill_suggestion = SkillSuggestion.new(params[:skill_suggestion])

    respond_to do |format|
      if @skill_suggestion.save
        format.html { redirect_to @skill_suggestion, notice: 'Skill suggestion was successfully created.' }
        format.json { render json: @skill_suggestion, status: :created, location: @skill_suggestion }
      else
        format.html { render action: "new" }
        format.json { render json: @skill_suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /skill_suggestions/1
  # PUT /skill_suggestions/1.json
  def update
    @skill_suggestion = SkillSuggestion.find(params[:id])

    respond_to do |format|
      if @skill_suggestion.update_attributes(params[:skill_suggestion])
        format.html { redirect_to @skill_suggestion, notice: 'Skill suggestion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @skill_suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skill_suggestions/1
  # DELETE /skill_suggestions/1.json
  def destroy
    @skill_suggestion = SkillSuggestion.find(params[:id])
    @skill_suggestion.destroy

    respond_to do |format|
      format.html { redirect_to skill_suggestions_url }
      format.json { head :no_content }
    end
  end
  
	def ajax_add_skill
		bid = params[:bid]
		guid = params[:private_guid]
		skill = params[:skill]
		skill_suggestion = SkillSuggestion.new(:bid => bid, :resume_doc_guid => guid, :skill => skill)
		skill_suggestion.save();
		render :json => {}.to_json
	end
	
	def ajax_remove_skill
		bid = cookies[:bid]
		id = params[:id]
		skill_suggestion = SkillSuggestion.find_by_id_and_bid(id, bid)
		if skill_suggestion
			skill_suggestion.destroy
		end
		render :json => {}.to_json
	end
end

app/helpers/skill_suggestions_helper.rb
module SkillSuggestionsHelper
end

app/views/skill_suggestions/_form.html.erb
<%= form_for(@skill_suggestion) do |f| %>
  <% if @skill_suggestion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skill_suggestion.errors.count, "error") %> prohibited this skill_suggestion from being saved:</h2>

      <ul>
      <% @skill_suggestion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :skill %><br />
    <%= f.text_field :skill %>
  </div>
  <div class="field">
    <%= f.label :resume_doc_guid %><br />
    <%= f.text_field :resume_doc_guid %>
  </div>
  <div class="field">
    <%= f.label :bid %><br />
    <%= f.text_field :bid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/skill_suggestions/edit.html.erb
<h1>Editing skill_suggestion</h1>

<%= render 'form' %>

<%= link_to 'Show', @skill_suggestion %> |
<%= link_to 'Back', skill_suggestions_path %>

app/views/skill_suggestions/index.html.erb
<h1>Listing skill_suggestions</h1>

<table>
  <tr>
    <th>Skill</th>
    <th>Resume doc guid</th>
    <th>Bid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @skill_suggestions.each do |skill_suggestion| %>
  <tr>
    <td><%= skill_suggestion.skill %></td>
    <td><%= skill_suggestion.resume_doc_guid %></td>
    <td><%= skill_suggestion.bid %></td>
    <td><%= link_to 'Show', skill_suggestion %></td>
    <td><%= link_to 'Edit', edit_skill_suggestion_path(skill_suggestion) %></td>
    <td><%= link_to 'Destroy', skill_suggestion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Skill suggestion', new_skill_suggestion_path %>

app/views/skill_suggestions/new.html.erb
<h1>New skill_suggestion</h1>

<%= render 'form' %>

<%= link_to 'Back', skill_suggestions_path %>

app/views/skill_suggestions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Skill:</b>
  <%= @skill_suggestion.skill %>
</p>

<p>
  <b>Resume doc guid:</b>
  <%= @skill_suggestion.resume_doc_guid %>
</p>

<p>
  <b>Bid:</b>
  <%= @skill_suggestion.bid %>
</p>


<%= link_to 'Edit', edit_skill_suggestion_path(@skill_suggestion) %> |
<%= link_to 'Back', skill_suggestions_path %>